const w = (en, tr, level, exEn, exTr) => ({ en, tr, level, exEn, exTr });

export const sectors = [
  {
    anchor: 'education',
    titleTr: 'Eğitim ve Üniversite',
    titleEn: 'Education and University',
    words: [
      w('campus', 'kampüs', 'A2', 'Our campus is near the city centre.', 'Kampüsümüz şehir merkezine yakın.'),
      w('lecture', 'ders, konferans', 'A2', 'The lecture starts at nine o\'clock.', 'Ders saat dokuzda başlıyor.'),
      w('degree', 'derece', 'A2', 'She wants a degree in engineering.', 'Mühendislik alanında bir derece istiyor.'),
      w('exam', 'sınav', 'A2', 'I studied hard for the final exam.', 'Final sınavı için çok çalıştım.'),
      w('student', 'öğrenci', 'A2', 'Every student needs a library card.', 'Her öğrencinin bir kütüphane kartına ihtiyacı var.'),
      w('teacher', 'öğretmen', 'A2', 'The teacher explained the grammar clearly.', 'Öğretmen dilbilgisini açıkça anlattı.'),
      w('classroom', 'sınıf', 'A2', 'The classroom has twenty desks.', 'Sınıfta yirmi sıra var.'),
      w('homework', 'ödev', 'A2', 'I finished my homework before dinner.', 'Akşam yemeğinden önce ödevimi bitirdim.'),
      w('scholarship', 'burs', 'B1', 'He won a scholarship to study abroad.', 'Yurtdışında okumak için burs kazandı.'),
      w('tuition', 'öğrenim ücreti', 'B1', 'Tuition fees have increased this year.', 'Bu yıl öğrenim ücretleri arttı.'),
      w('curriculum', 'müfredat', 'B1', 'The curriculum includes writing and speaking.', 'Müfredat yazma ve konuşmayı içeriyor.'),
      w('semester', 'dönem', 'B1', 'The new semester begins in September.', 'Yeni dönem Eylülde başlıyor.'),
      w('assignment', 'ödev, görev', 'B1', 'The assignment is due on Friday.', 'Ödevin teslim tarihi Cuma.'),
      w('graduate', 'mezun olmak', 'B1', 'She will graduate next summer.', 'Gelecek yaz mezun olacak.'),
      w('enroll', 'kayıt yaptırmak', 'B1', 'Students must enroll online this week.', 'Öğrenciler bu hafta çevrimiçi kayıt yaptırmalı.'),
      w('research', 'araştırma', 'B1', 'University research can improve public health.', 'Üniversite araştıması kamu sağlığını iyileştirebilir.'),
      w('literacy', 'okuryazarlık', 'B1', 'Digital literacy is important for students.', 'Dijital okuryazarlık öğrenciler için önemlidir.'),
      w('attendance', 'devam, katılım', 'B1', 'Good attendance helps you pass the course.', 'İyi devam dersten geçmene yardımcı olur.'),
      w('discipline', 'disiplin', 'B1', 'Self-discipline is key to academic success.', 'Öz disiplin akademik başarının anahtarıdır.'),
      w('mentoring', 'mentorluk', 'B1+', 'Mentoring programmes support first-year students.', 'Mentorluk programları birinci sınıf öğrencilerini destekler.'),
      w('plagiarism', 'intihal', 'B1+', 'Plagiarism can lead to serious penalties.', 'İntihal ciddi yaptırımlara yol açabilir.'),
      w('accreditation', 'akreditasyon', 'B1+', 'The faculty received international accreditation.', 'Fakülte uluslararası akreditasyon aldı.'),
      w('pedagogy', 'pedagoji', 'B1+', 'Modern pedagogy focuses on active learning.', 'Modern pedagoji etkin öğrenmeye odaklanır.'),
      w('thesis', 'tez', 'B1+', 'She is writing her thesis on climate policy.', 'İklim politikası üzerine tez yazıyor.'),
      w('postgraduate', 'lisansüstü', 'B1+', 'Postgraduate courses require strong English.', 'Lisansüstü dersler iyi İngilizce gerektirir.'),
      w('vocational', 'mesleki', 'B1+', 'Vocational training prepares students for jobs.', 'Mesleki eğitim öğrencileri işe hazırlar.'),
      w('equitable', 'adil, eşitlikçi', 'B1+', 'Schools should offer equitable access to education.', 'Okullar eğitime adil erişim sunmalıdır.'),
    ],
  },
  {
    anchor: 'health',
    titleTr: 'Sağlık',
    titleEn: 'Health',
    words: [
      w('doctor', 'doktor', 'A2', 'You should see a doctor if you feel worse.', 'Kötü hissediyorsan bir doktora gitmelisin.'),
      w('hospital', 'hastane', 'A2', 'The hospital is open twenty-four hours.', 'Hastane yirmi dört saat açık.'),
      w('medicine', 'ilaç, tıp', 'A2', 'Take your medicine after breakfast.', 'İlacını kahvaltıdan sonra al.'),
      w('pain', 'ağrı', 'A2', 'She has pain in her back.', 'Sırtında ağrı var.'),
      w('fever', 'ateş', 'A2', 'A high fever can be dangerous.', 'Yüksek ateş tehlikeli olabilir.'),
      w('nurse', 'hemşire', 'A2', 'The nurse checked my blood pressure.', 'Hemşire tansiyonumu ölçtü.'),
      w('patient', 'hasta', 'A2', 'The patient is resting in bed.', 'Hasta yatakta dinleniyor.'),
      w('healthy', 'sağlıklı', 'A2', 'A balanced diet keeps you healthy.', 'Dengeli beslenme seni sağlıklı tutar.'),
      w('treatment', 'tedavi', 'B1', 'Early treatment saves many lives.', 'Erken tedavi birçok hayat kurtarır.'),
      w('symptom', 'belirti, semptom', 'B1', 'Fever is a common symptom of flu.', 'Ateş gribin yaygın bir belirtisidir.'),
      w('prevention', 'önleme', 'B1', 'Prevention is better than cure.', 'Önlem tedaviden iyidir.'),
      w('vaccine', 'aşı', 'B1', 'The vaccine protects against serious illness.', 'Aşı ciddi hastalıklara karşı korur.'),
      w('mental', 'zihinsel, ruhsal', 'B1', 'Mental health matters as much as physical health.', 'Ruh sağlığı fiziksel sağlık kadar önemlidir.'),
      w('chronic', 'kronik', 'B1', 'Chronic diseases need long-term care.', 'Kronik hastalıklar uzun süreli bakım gerektirir.'),
      w('infection', 'enfeksiyon', 'B1', 'Wash your hands to prevent infection.', 'Enfeksiyonu önlemek için ellerini yıka.'),
      w('nutrition', 'beslenme', 'B1', 'Good nutrition supports the immune system.', 'İyi beslenme bağışıklık sistemini destekler.'),
      w('obesity', 'obezite', 'B1', 'Obesity is rising in many countries.', 'Obezite birçok ülkede artıyor.'),
      w('hygiene', 'hijyen', 'B1', 'Public hygiene reduces disease spread.', 'Kamu hijyeni hastalık yayılımını azaltır.'),
      w('rehabilitation', 'rehabilitasyon', 'B1', 'Rehabilitation helps patients recover mobility.', 'Rehabilitasyon hastaların hareket kabiliyetini geri kazanmasına yardımcı olur.'),
      w('epidemic', 'salgın', 'B1+', 'The epidemic forced hospitals to expand.', 'Salgın hastaneleri genişletmeye zorladı.'),
      w('immunity', 'bağışıklık', 'B1+', 'Vaccination builds immunity over time.', 'Aşılama zamanla bağışıklık oluşturur.'),
      w('diagnosis', 'teşhis', 'B1+', 'Accurate diagnosis improves treatment outcomes.', 'Doğru teşhis tedavi sonuçlarını iyileştirir.'),
      w('wellbeing', 'refah, iyi olma hali', 'B1+', 'Exercise improves overall wellbeing.', 'Egzersiz genel refahı artırır.'),
      w('healthcare', 'sağlık hizmetleri', 'B1+', 'Everyone deserves access to affordable healthcare.', 'Herkes uygun fiyatlı sağlık hizmetlerine erişmeyi hak eder.'),
      w('pandemic', 'pandemi', 'B1+', 'The pandemic changed how we work and study.', 'Pandemi çalışma ve öğrenme biçimimizi değiştirdi.'),
      w('sedentary', 'hareketsiz', 'B1+', 'A sedentary lifestyle increases health risks.', 'Hareketsiz yaşam tarzı sağlık risklerini artırır.'),
      w('therapeutic', 'terapötik, tedavi edici', 'B1+', 'Therapeutic exercise can reduce stress.', 'Terapötik egzersiz stresi azaltabilir.'),
    ],
  },
  {
    anchor: 'environment',
    titleTr: 'Çevre ve İklim',
    titleEn: 'Environment and Climate',
    words: [
      w('pollution', 'kirlilik', 'A2', 'Air pollution is worse in big cities.', 'Hava kirliliği büyük şehirlerde daha kötü.'),
      w('recycle', 'geri dönüştürmek', 'A2', 'We recycle paper and plastic at home.', 'Evde kağıt ve plastiği geri dönüştürüyoruz.'),
      w('tree', 'ağaç', 'A2', 'They planted a tree in the park.', 'Parka bir ağaç diktiler.'),
      w('water', 'su', 'A2', 'Clean water is essential for life.', 'Temiz su yaşam için gereklidir.'),
      w('waste', 'atık', 'A2', 'Reduce waste by buying less plastic.', 'Daha az plastik alarak atığı azalt.'),
      w('climate', 'iklim', 'A2', 'The climate is getting warmer every year.', 'İklim her yıl daha sıcak hale geliyor.'),
      w('nature', 'doğa', 'A2', 'We should protect nature for future generations.', 'Gelecek nesiller için doğayı korumalıyız.'),
      w('energy', 'enerji', 'A2', 'Solar energy is cheaper than before.', 'Güneş enerjisi eskisinden daha ucuz.'),
      w('emission', 'emisyon, salınım', 'B1', 'Car emissions contribute to global warming.', 'Araba emisyonları küresel ısınmaya katkıda bulunur.'),
      w('renewable', 'yenilenebilir', 'B1', 'Renewable energy creates fewer greenhouse gases.', 'Yenilenebilir enerji daha az sera gazı üretir.'),
      w('biodiversity', 'biyoçeşitlilik', 'B1', 'Forests support rich biodiversity.', 'Ormanlar zengin biyoçeşitliliği destekler.'),
      w('deforestation', 'ormansızlaşma', 'B1', 'Deforestation destroys animal habitats.', 'Ormansızlaşma hayvan habitatlarını yok eder.'),
      w('drought', 'kuraklık', 'B1', 'Drought affects farmers and food prices.', 'Kuraklık çiftçileri ve gıda fiyatlarını etkiler.'),
      w('ecosystem', 'ekosistem', 'B1', 'Pollution harms the local ecosystem.', 'Kirlilik yerel ekosisteme zarar verir.'),
      w('sustainable', 'sürdürülebilir', 'B1', 'We need sustainable farming methods.', 'Sürdürülebilir tarım yöntemlerine ihtiyacımız var.'),
      w('conservation', 'koruma', 'B1', 'Wildlife conservation protects endangered species.', 'Yaban hayatı koruma nesli tükenmekte olan türleri korur.'),
      w('carbon', 'karbon', 'B1', 'Companies aim to reduce carbon footprints.', 'Şirketler karbon ayak izini azaltmayı hedefliyor.'),
      w('habitat', 'yaşam alanı', 'B1', 'Urban growth destroys natural habitats.', 'Kentsel büyüme doğal yaşam alanlarını yok eder.'),
      w('erosion', 'erozyon', 'B1', 'Soil erosion reduces crop yields.', 'Toprak erozyonu mahsul verimini düşürür.'),
      w('mitigation', 'hafifletme, azaltma', 'B1+', 'Climate mitigation requires global cooperation.', 'İklim hafifletmesi küresel iş birliği gerektirir.'),
      w('degradation', 'bozulma', 'B1+', 'Environmental degradation threatens water supplies.', 'Çevresel bozulma su kaynaklarını tehdit eder.'),
      w('extinction', 'neslin tükenmesi', 'B1+', 'Habitat loss can lead to species extinction.', 'Habitat kaybı türlerin neslinin tükenmesine yol açabilir.'),
      w('geothermal', 'jeotermal', 'B1+', 'Geothermal plants produce clean electricity.', 'Jeotermal santraller temiz elektrik üretir.'),
      w('anthropogenic', 'insan kaynaklı', 'B1+', 'Much warming is anthropogenic in origin.', 'Isınmanın büyük kısmı insan kaynaklıdır.'),
      w('resilience', 'dayanıklılık', 'B1+', 'Coastal cities need climate resilience plans.', 'Kıyı şehirlerinin iklim dayanıklılık planlarına ihtiyacı var.'),
      w('afforestation', 'ağaçlandırma', 'B1+', 'Afforestation projects restore damaged land.', 'Ağaçlandırma projeleri zarar görmüş araziyi restore eder.'),
      w('decarbonisation', 'karbonsuzlaştırma', 'B1+', 'Decarbonisation of transport is a long-term goal.', 'Ulaşımın karbonsuzlaştırılması uzun vadeli bir hedeftir.'),
    ],
  },
  {
    anchor: 'technology',
    titleTr: 'Teknoloji ve Dijital Yaşam',
    titleEn: 'Technology and Digital Life',
    words: [
      w('computer', 'bilgisayar', 'A2', 'I use my computer for online classes.', 'Çevrimiçi dersler için bilgisayarımı kullanıyorum.'),
      w('internet', 'internet', 'A2', 'The internet helps students find information.', 'İnternet öğrencilerin bilgi bulmasına yardımcı olur.'),
      w('phone', 'telefon', 'A2', 'Put your phone on silent during the lecture.', 'Ders sırasında telefonunu sessize al.'),
      w('email', 'e-posta', 'A2', 'Please send the report by email.', 'Lütfen raporu e-posta ile gönder.'),
      w('website', 'web sitesi', 'A2', 'The university website lists all courses.', 'Üniversite web sitesi tüm dersleri listeler.'),
      w('password', 'şifre', 'A2', 'Choose a strong password for your account.', 'Hesabın için güçlü bir şifre seç.'),
      w('download', 'indirmek', 'A2', 'You can download the slides from Moodle.', 'Slaytları Moodle\'dan indirebilirsin.'),
      w('online', 'çevrimiçi', 'A2', 'Many students prefer online study groups.', 'Birçok öğrenci çevrimiçi çalışma gruplarını tercih eder.'),
      w('software', 'yazılım', 'B1', 'New software makes editing faster.', 'Yeni yazılım düzenlemeyi hızlandırır.'),
      w('device', 'cihaz', 'B1', 'Each student needs a reliable device.', 'Her öğrencinin güvenilir bir cihaza ihtiyacı var.'),
      w('digital', 'dijital', 'B1', 'Digital skills are essential in modern jobs.', 'Dijital beceriler modern işlerde gereklidir.'),
      w('cybersecurity', 'siber güvenlik', 'B1', 'Cybersecurity protects personal data online.', 'Siber güvenlik çevrimiçi kişisel verileri korur.'),
      w('algorithm', 'algoritma', 'B1', 'Social media uses algorithms to suggest content.', 'Sosyal medya içerik önermek için algoritma kullanır.'),
      w('automation', 'otomasyon', 'B1', 'Automation may change many workplaces.', 'Otomasyon birçok iş yerini değiştirebilir.'),
      w('innovation', 'yenilik', 'B1', 'Innovation drives economic growth.', 'Yenilik ekonomik büyümeyi tetikler.'),
      w('artificial', 'yapay', 'B1', 'Artificial intelligence assists medical diagnosis.', 'Yapay zeka tıbbi teşhise yardımcı olur.'),
      w('privacy', 'mahremiyet, gizlilik', 'B1', 'Users worry about privacy on social apps.', 'Kullanıcılar sosyal uygulamalarda gizlilik konusunda endişeli.'),
      w('connectivity', 'bağlantı', 'B1', 'Rural areas still lack fast connectivity.', 'Kırsal bölgelerde hâlâ hızlı bağlantı eksik.'),
      w('bandwidth', 'bant genişliği', 'B1', 'Video lectures need enough bandwidth.', 'Video dersler yeterli bant genişliği gerektirir.'),
      w('encryption', 'şifreleme', 'B1+', 'Encryption keeps messages secure.', 'Şifreleme mesajları güvende tutar.'),
      w('blockchain', 'blok zinciri', 'B1+', 'Blockchain technology supports secure transactions.', 'Blok zinciri teknolojisi güvenli işlemleri destekler.'),
      w('prototype', 'prototip', 'B1+', 'Engineers tested a prototype of the app.', 'Mühendisler uygulamanın bir prototipini test etti.'),
      w('disruptive', 'yıkıcı, devrim niteliğinde', 'B1+', 'Disruptive tech can replace old business models.', 'Yıkıcı teknoloji eski iş modellerinin yerini alabilir.'),
      w('interoperability', 'birlikte çalışabilirlik', 'B1+', 'Systems need interoperability to share data safely.', 'Sistemlerin veriyi güvenle paylaşması için birlikte çalışabilirlik gerekir.'),
      w('biometric', 'biyometrik', 'B1+', 'Biometric login is common on new phones.', 'Biyometrik giriş yeni telefonlarda yaygın.'),
      w('technological', 'teknolojik', 'B1+', 'Technological change affects education policy.', 'Teknolojik değişim eğitim politikasını etkiler.'),
      w('digitisation', 'dijitalleştirme', 'B1+', 'Digitisation of records saves office space.', 'Kayıtların dijitalleştirilmesi ofis alanından tasarruf sağlar.'),
    ],
  },
  {
    anchor: 'work',
    titleTr: 'İş ve Kariyer',
    titleEn: 'Work and Career',
    words: [
      w('job', 'iş', 'A2', 'She found a part-time job near campus.', 'Kampüs yakınında yarı zamanlı bir iş buldu.'),
      w('boss', 'patron', 'A2', 'My boss is fair but very busy.', 'Patronum adil ama çok meşgul.'),
      w('salary', 'maaş', 'A2', 'His salary increased after the promotion.', 'Terfi sonrası maaşı arttı.'),
      w('office', 'ofis', 'A2', 'The office closes at six in the evening.', 'Ofis akşam altıda kapanıyor.'),
      w('colleague', 'iş arkadaşı', 'A2', 'My colleague helped me with the report.', 'İş arkadaşım raporda bana yardım etti.'),
      w('interview', 'mülakat', 'A2', 'I have a job interview on Monday.', 'Pazartesi bir iş mülakatım var.'),
      w('CV', 'özgeçmiş', 'A2', 'Update your CV before applying.', 'Başvurmadan önce özgeçmişini güncelle.'),
      w('shift', 'vardiya', 'A2', 'Night shifts are tiring but well paid.', 'Gece vardiyaları yorucu ama iyi ücretli.'),
      w('employer', 'işveren', 'B1', 'A good employer offers training opportunities.', 'İyi bir işveren eğitim fırsatları sunar.'),
      w('employee', 'çalışan', 'B1', 'Every employee must follow safety rules.', 'Her çalışan güvenlik kurallarına uymalıdır.'),
      w('promotion', 'terfi', 'B1', 'Hard work can lead to promotion.', 'Sıkı çalışma terfiye yol açabilir.'),
      w('unemployment', 'işsizlik', 'B1', 'Unemployment rose during the economic crisis.', 'Ekonomik kriz sırasında işsizlik arttı.'),
      w('workplace', 'iş yeri', 'B1', 'A safe workplace reduces accidents.', 'Güvenli bir iş yeri kazaları azaltır.'),
      w('freelance', 'serbest çalışan', 'B1', 'She works as a freelance graphic designer.', 'Serbest grafik tasarımcı olarak çalışıyor.'),
      w('deadline', 'son teslim tarihi', 'B1', 'We must meet the project deadline.', 'Proje son teslim tarihine uymalıyız.'),
      w('productivity', 'verimlilik', 'B1', 'Short breaks can improve productivity.', 'Kısa molalar verimliliği artırabilir.'),
      w('recruitment', 'işe alım', 'B1', 'Online recruitment saves time for HR teams.', 'Çevrimiçi işe alım İK ekiplerine zaman kazandırır.'),
      w('retirement', 'emeklilik', 'B1', 'He plans retirement at the age of sixty.', 'Altmış yaşında emeklilik planlıyor.'),
      w('overtime', 'fazla mesai', 'B1', 'Overtime pay is higher on weekends.', 'Hafta sonu fazla mesai ücreti daha yüksektir.'),
      w('entrepreneur', 'girişimci', 'B1+', 'The entrepreneur started a small tech firm.', 'Girişimci küçük bir teknoloji firması kurdu.'),
      w('internship', 'staj', 'B1+', 'An internship gives valuable work experience.', 'Staj değerli iş deneyimi kazandırır.'),
      w('redundancy', 'işten çıkarma', 'B1+', 'Redundancy programmes affected many workers.', 'İşten çıkarma programları birçok işçiyi etkiledi.'),
      w('remuneration', 'ücretlendirme', 'B1+', 'Fair remuneration improves staff motivation.', 'Adil ücretlendirme personel motivasyonunu artırır.'),
      w('telecommuting', 'uzaktan çalışma', 'B1+', 'Telecommuting became normal after the pandemic.', 'Pandemi sonrası uzaktan çalışma normalleşti.'),
      w('probation', 'deneme süresi', 'B1+', 'New staff complete a three-month probation period.', 'Yeni personel üç aylık deneme süresini tamamlar.'),
      w('underemployment', 'yetersiz istihdam', 'B1+', 'Underemployment is a problem for young graduates.', 'Yetersiz istihdam genç mezunlar için bir sorundur.'),
      w('multitasking', 'çoklu görev', 'B1+', 'Multitasking can reduce focus at work.', 'Çoklu görev işte odağı azaltabilir.'),
    ],
  },
  {
    anchor: 'economy',
    titleTr: 'Ekonomi ve Para',
    titleEn: 'Economy and Money',
    words: [
      w('money', 'para', 'A2', 'Students need money for books and transport.', 'Öğrencilerin kitap ve ulaşım için paraya ihtiyacı var.'),
      w('price', 'fiyat', 'A2', 'Food prices went up last month.', 'Gıda fiyatları geçen ay arttı.'),
      w('bank', 'banka', 'A2', 'I opened a bank account yesterday.', 'Dün bir banka hesabı açtım.'),
      w('tax', 'vergi', 'A2', 'Everyone pays tax on their income.', 'Herkes gelirine vergi öder.'),
      w('cost', 'maliyet, bedel', 'A2', 'The cost of living is high in Istanbul.', 'İstanbul\'da yaşam maliyeti yüksek.'),
      w('cheap', 'ucuz', 'A2', 'Local markets sell cheap vegetables.', 'Yerel pazarlar ucuz sebze satar.'),
      w('expensive', 'pahalı', 'A2', 'Rent is expensive near the university.', 'Üniversite yakınında kira pahalı.'),
      w('budget', 'bütçe', 'A2', 'Make a monthly budget for your expenses.', 'Giderlerin için aylık bir bütçe yap.'),
      w('inflation', 'enflasyon', 'B1', 'Inflation reduces the value of savings.', 'Enflasyon birikimlerin değerini düşürür.'),
      w('investment', 'yatırım', 'B1', 'Green investment supports clean energy projects.', 'Yeşil yatırım temiz enerji projelerini destekler.'),
      w('currency', 'para birimi', 'B1', 'The currency fell against the dollar.', 'Para birimi dolara karşı değer kaybetti.'),
      w('recession', 'durgunluk, resesyon', 'B1', 'A recession can increase unemployment.', 'Resesyon işsizliği artırabilir.'),
      w('subsidy', 'sübvansiyon, devlet desteği', 'B1', 'The government gives subsidies for solar panels.', 'Hükümet güneş panelleri için sübvansiyon veriyor.'),
      w('export', 'ihracat', 'B1', 'Turkey exports textiles and food products.', 'Türkiye tekstil ve gıda ürünleri ihraç eder.'),
      w('import', 'ithalat', 'B1', 'Oil imports affect the trade balance.', 'Petrol ithalatı ticaret dengesini etkiler.'),
      w('poverty', 'yoksulluk', 'B1', 'Education can help reduce poverty.', 'Eğitim yoksulluğu azaltmaya yardımcı olabilir.'),
      w('wealth', 'servet, zenginlik', 'B1', 'Wealth is unevenly distributed in society.', 'Servet toplumda eşitsiz dağılmıştır.'),
      w('consumer', 'tüketici', 'B1', 'Consumers compare prices before buying.', 'Tüketiciler alışverişten önce fiyatları karşılaştırır.'),
      w('debt', 'borç', 'B1', 'Student debt worries many graduates.', 'Öğrenci borcu birçok mezunu endişelendiriyor.'),
      w('fiscal', 'mali, bütçe ile ilgili', 'B1+', 'Fiscal policy affects public spending.', 'Malî politika kamu harcamalarını etkiler.'),
      w('austerity', 'kemeri sıkma', 'B1+', 'Austerity measures cut social programmes.', 'Kemer sıkma önlemleri sosyal programları kesti.'),
      w('stagnation', 'durgunluk', 'B1+', 'Economic stagnation limits job creation.', 'Ekonomik durgunluk iş yaratmayı sınırlar.'),
      w('commodity', 'emtia', 'B1+', 'Commodity prices fluctuate on global markets.', 'Emtia fiyatları küresel piyasalarda dalgalanır.'),
      w('procurement', 'tedarik, satın alma', 'B1+', 'Public procurement must follow transparent rules.', 'Kamu tedariki şeffaf kurallara uymalıdır.'),
      w('liquidity', 'likidite, nakit akışı', 'B1+', 'Banks need liquidity during financial crises.', 'Bankaların finansal krizlerde likiditeye ihtiyacı vardır.'),
      w('macroeconomic', 'makroekonomik', 'B1+', 'Macroeconomic trends influence exchange rates.', 'Makroekonomik eğilimler döviz kurlarını etkiler.'),
      w('inequality', 'eşitsizlik', 'B1+', 'Income inequality remains a political issue.', 'Gelir eşitsizliği siyasi bir mesele olmaya devam ediyor.'),
    ],
  },
  {
    anchor: 'government',
    titleTr: 'Devlet ve Toplum',
    titleEn: 'Government and Society',
    words: [
      w('vote', 'oy vermek', 'A2', 'Citizens vote in national elections.', 'Vatandaşlar ulusal seçimlerde oy kullanır.'),
      w('law', 'yasa', 'A2', 'Everyone must respect the law.', 'Herkes yasaya saygı göstermelidir.'),
      w('mayor', 'belediye başkanı', 'A2', 'The mayor opened a new library.', 'Belediye başkanı yeni bir kütüphane açtı.'),
      w('court', 'mahkeme', 'A2', 'The court heard the case yesterday.', 'Mahkeme davayı dün görüştü.'),
      w('citizen', 'vatandaş', 'A2', 'Every citizen has rights and duties.', 'Her vatandaşın hak ve görevleri vardır.'),
      w('police', 'polis', 'A2', 'Police keep order in the city centre.', 'Polis şehir merkezinde düzeni sağlar.'),
      w('army', 'ordu', 'A2', 'The army helped after the earthquake.', 'Ordu depremden sonra yardım etti.'),
      w('flag', 'bayrak', 'A2', 'The flag flew above the town hall.', 'Bayrak belediye binasının üzerinde dalgalandı.'),
      w('democracy', 'demokrasi', 'B1', 'Democracy depends on free elections.', 'Demokrasi özgür seçimlere bağlıdır.'),
      w('policy', 'politika', 'B1', 'Education policy affects every student.', 'Eğitim politikası her öğrenciyi etkiler.'),
      w('minister', 'bakan', 'B1', 'The health minister announced new clinics.', 'Sağlık bakanı yeni klinikler duyurdu.'),
      w('parliament', 'parlamento', 'B1', 'Parliament debated the new budget law.', 'Parlamento yeni bütçe yasasını tartıştı.'),
      w('referendum', 'referandum', 'B1', 'A referendum decided the constitutional change.', 'Anayasa değişikliğine referandum karar verdi.'),
      w('welfare', 'refah, sosyal yardım', 'B1', 'Welfare programmes support low-income families.', 'Sosyal yardım programları düşük gelirli aileleri destekler.'),
      w('bureaucracy', 'bürokrasi', 'B1', 'Bureaucracy slows some permit applications.', 'Bürokrasi bazı izin başvurularını yavaşlatır.'),
      w('sovereignty', 'egemenlik', 'B1', 'National sovereignty is a sensitive topic.', 'Ulusal egemenlik hassas bir konudur.'),
      w('legislation', 'mevzuat', 'B1', 'New legislation protects consumer rights.', 'Yeni mevzuat tüketici haklarını korur.'),
      w('municipality', 'belediye', 'B1', 'The municipality repaired the main street.', 'Belediye ana caddede onarım yaptı.'),
      w('civil', 'sivil', 'B1', 'Civil society groups promote human rights.', 'Sivil toplum kuruluşları insan haklarını savunur.'),
      w('governance', 'yönetişim', 'B1+', 'Good governance requires transparency.', 'İyi yönetişim şeffaflık gerektirir.'),
      w('authoritarian', 'otoriter', 'B1+', 'Authoritarian regimes limit press freedom.', 'Otoriter rejimler basın özgürlüğünü kısıtlar.'),
      w('constituency', 'seçim bölgesi', 'B1+', 'The MP visited every constituency last year.', 'Milletvekili geçen yıl her seçim bölgesini ziyaret etti.'),
      w('devolution', 'yetki devri', 'B1+', 'Devolution gives more power to local councils.', 'Yetki devri yerel meclislere daha fazla güç verir.'),
      w('pluralism', 'çoğulculuk', 'B1+', 'Political pluralism allows diverse opinions.', 'Siyasi çoğulculuk farklı görüşlere izin verir.'),
      w('accountability', 'hesap verebilirlik', 'B1+', 'Public officials need accountability to voters.', 'Kamu görevlilerinin seçmenlere karşı hesap verebilirliği gerekir.'),
      w('diplomatic', 'diplomatik', 'B1+', 'Diplomatic talks eased border tensions.', 'Diplomatik görüşmeler sınır gerilimini hafifletti.'),
      w('federalism', 'federe sistem', 'B1+', 'Federalism divides power between regions and centre.', 'Federalizm gücü bölgeler ve merkez arasında böler.'),
    ],
  },
  {
    anchor: 'law',
    titleTr: 'Hukuk ve Suç',
    titleEn: 'Law and Crime',
    words: [
      w('crime', 'suç', 'A2', 'Crime rates fell in our district.', 'İlçemizde suç oranları düştü.'),
      w('robbery', 'soygun', 'A2', 'Robbery rates dropped in the city centre.', 'Şehir merkezinde soygun oranları düştü.'),
      w('judge', 'yargıç', 'A2', 'The judge listened to both sides.', 'Yargıç her iki tarafı da dinledi.'),
      w('prison', 'hapishane', 'A2', 'He spent two years in prison.', 'İki yıl hapishanede kaldı.'),
      w('lawyer', 'avukat', 'A2', 'She hired a lawyer for the trial.', 'Duruşma için bir avukat tuttu.'),
      w('guilty', 'suçlu', 'A2', 'The jury found him guilty.', 'Jüri onu suçlu buldu.'),
      w('innocent', 'masum', 'A2', 'The court said he was innocent.', 'Mahkeme onun masum olduğunu söyledi.'),
      w('fine', 'para cezası', 'A2', 'He paid a fine for speeding.', 'Hız sınırını aştığı için para cezası ödedi.'),
      w('trial', 'duruşma, yargılama', 'B1', 'The trial lasted three weeks.', 'Duruşma üç hafta sürdü.'),
      w('evidence', 'kanıt', 'B1', 'DNA evidence proved his innocence.', 'DNA kanıtı masumiyetini kanıtladı.'),
      w('sentence', 'ceza, hüküm', 'B1', 'The judge gave a ten-year sentence.', 'Yargıç on yıllık ceza verdi.'),
      w('witness', 'tanık', 'B1', 'The witness described the accident clearly.', 'Tanık kazayı açıkça anlattı.'),
      w('fraud', 'dolandırıcılık', 'B1', 'Online fraud targets elderly users.', 'Çevrimiçi dolandırıcılık yaşlı kullanıcıları hedef alır.'),
      w('theft', 'hırsızlık', 'B1', 'Theft from cars increased last summer.', 'Geçen yaz araçlardan hırsızlık arttı.'),
      w('regulation', 'düzenleme, yönetmelik', 'B1', 'New regulations control air pollution.', 'Yeni düzenlemeler hava kirliliğini kontrol eder.'),
      w('offence', 'suç, kabahat', 'B1', 'Minor offences may receive only a fine.', 'Küçük suçlar yalnızca para cezası alabilir.'),
      w('prosecution', 'kovuşturma', 'B1', 'Prosecution must prove guilt beyond doubt.', 'Kovuşturma suçu şüpheden öte kanıtlamalıdır.'),
      w('verdict', 'karar, hüküm', 'B1', 'The verdict surprised many journalists.', 'Karar birçok gazeteciyi şaşırttı.'),
      w('bail', 'kefalet', 'B1', 'The suspect was released on bail.', 'Şüpheli kefaletle serbest bırakıldı.'),
      w('jurisdiction', 'yargı yetkisi', 'B1+', 'The case falls under local jurisdiction.', 'Dava yerel yargı yetkisine girer.'),
      w('litigation', 'dava süreci', 'B1+', 'Litigation can be slow and expensive.', 'Dava süreci yavaş ve pahalı olabilir.'),
      w('corruption', 'yolsuzluk', 'B1+', 'Corruption undermines public trust.', 'Yolsuzluk kamu güvenini zedeler.'),
      w('acquittal', 'beraat', 'B1+', 'The acquittal ended years of legal battle.', 'Beraat yıllarca süren hukuk mücadelesini bitirdi.'),
      w('culpable', 'suçlu, sorumlu', 'B1+', 'The company was found culpable for the spill.', 'Şirket sızıntıdan sorumlu bulundu.'),
      w('statutory', 'yasal, kanuni', 'B1+', 'Statutory rights protect employees at work.', 'Yasal haklar işte çalışanları korur.'),
      w('recidivism', 'tekrar suç işleme', 'B1+', 'Education programmes aim to reduce recidivism.', 'Eğitim programları tekrar suç işlemeyi azaltmayı hedefler.'),
      w('extradition', 'iade', 'B1+', 'Extradition treaties help fight international crime.', 'İade anlaşmaları uluslararası suçla mücadeleye yardımcı olur.'),
    ],
  },
  {
    anchor: 'transport',
    titleTr: 'Ulaşım ve Seyahat',
    titleEn: 'Transport and Travel',
    words: [
      w('bus', 'otobüs', 'A2', 'I take the bus to university every day.', 'Her gün üniversiteye otobüsle gidiyorum.'),
      w('train', 'tren', 'A2', 'The train to Ankara leaves at noon.', 'Ankara treni öğlen kalkıyor.'),
      w('ticket', 'bilet', 'A2', 'Buy your ticket before you board.', 'Binmeden önce biletinizi alın.'),
      w('airport', 'havalimanı', 'A2', 'We arrived at the airport two hours early.', 'Havalimanına iki saat erken vardık.'),
      w('flight', 'uçuş', 'A2', 'Our flight was delayed by bad weather.', 'Uçuşumuz kötü hava yüzünden gecikti.'),
      w('taxi', 'taksi', 'A2', 'A taxi took us to the hotel.', 'Bizi otele bir taksi götürdü.'),
      w('map', 'harita', 'A2', 'Use a map to find the old city.', 'Eski şehri bulmak için harita kullan.'),
      w('luggage', 'bagaj', 'A2', 'Do not leave your luggage unattended.', 'Bagajınızı gözetimsiz bırakmayın.'),
      w('traffic', 'trafik', 'B1', 'Traffic jams waste time every morning.', 'Trafik sıkışıklığı her sabah zaman kaybettirir.'),
      w('motorway', 'otoyol', 'B1', 'The new motorway shortened the journey.', 'Yeni otoyol yolculuğu kısalttı.'),
      w('commute', 'işe gidip gelme', 'B1', 'Many students commute from nearby towns.', 'Birçok öğrenci yakın kasabalardan işe gidip geliyor.'),
      w('pedestrian', 'yaya', 'B1', 'Pedestrian zones are safer in the centre.', 'Yaya bölgeleri merkezde daha güvenlidir.'),
      w('fare', 'ücret, tarife', 'B1', 'Bus fares increased this semester.', 'Otobüs ücretleri bu dönem arttı.'),
      w('delay', 'gecikme', 'B1', 'Train delays upset daily commuters.', 'Tren gecikmeleri günlük yolcuları üzer.'),
      w('destination', 'varış noktası', 'B1', 'Gaziantep is a popular tourist destination.', 'Gaziantep popüler bir turistik varış noktasıdır.'),
      w('infrastructure', 'altyapı', 'B1', 'Better infrastructure attracts investment.', 'Daha iyi altyapı yatırımı çeker.'),
      w('congestion', 'sıkışıklık', 'B1', 'Urban congestion harms air quality.', 'Kentsel sıkışıklık hava kalitesine zarar verir.'),
      w('aviation', 'havacılık', 'B1', 'Aviation emissions affect the climate.', 'Havacılık emisyonları iklimi etkiler.'),
      w('itinerary', 'seyahat programı', 'B1', 'Our itinerary includes two museums.', 'Seyahat programımız iki müzeyi içeriyor.'),
      w('logistics', 'lojistik', 'B1+', 'Efficient logistics reduce delivery costs.', 'Verimli lojistik teslimat maliyetlerini düşürür.'),
      w('electrification', 'elektrifikasyon', 'B1+', 'Rail electrification cuts carbon emissions.', 'Demiryolu elektrifikasyonu karbon emisyonlarını azaltır.'),
      w('intermodal', 'karma modlu', 'B1+', 'Intermodal hubs link buses, trains and bikes.', 'Karma modlu merkezler otobüs, tren ve bisikleti bağlar.'),
      w('light-rail', 'hafif raylı sistem', 'B1+', 'Light-rail lines connect suburbs to the centre.', 'Hafif raylı hatlar banliyöleri merkeze bağlar.'),
      w('accessibility', 'erişilebilirlik', 'B1+', 'Stations need accessibility for wheelchair users.', 'İstasyonların tekerlekli sandalye kullanıcıları için erişilebilir olması gerekir.'),
      w('carbon-neutral', 'karbon nötr', 'B1+', 'The city aims for carbon-neutral buses by 2030.', 'Şehir 2030\'a kadar karbon nötr otobüsler hedefliyor.'),
      w('transit-oriented', 'ulaşım odaklı', 'B1+', 'Transit-oriented planning reduces car use.', 'Ulaşım odaklı planlama araba kullanımını azaltır.'),
      w('wayfinding', 'yön bulma', 'B1+', 'Clear wayfinding helps visitors in large stations.', 'Net yön bulma büyük istasyonlarda ziyaretçilere yardımcı olur.'),
    ],
  },
  {
    anchor: 'food',
    titleTr: 'Yiyecek ve Beslenme',
    titleEn: 'Food and Nutrition',
    words: [
      w('bread', 'ekmek', 'A2', 'Fresh bread smells wonderful in the morning.', 'Taze ekmek sabahları harika kokar.'),
      w('dairy', 'süt ürünleri', 'A2', 'Dairy products need to stay cold.', 'Süt ürünleri soğuk kalmalıdır.'),
      w('fruit', 'meyve', 'A2', 'Eat fruit instead of sugary snacks.', 'Şekerli atıştırmalıklar yerine meyve ye.'),
      w('meat', 'et', 'A2', 'Some students do not eat meat.', 'Bazı öğrenciler et yemez.'),
      w('rice', 'pirinç', 'A2', 'Rice is cheap and easy to cook.', 'Pirinç ucuz ve pişirmesi kolaydır.'),
      w('breakfast', 'kahvaltı', 'A2', 'A good breakfast helps you concentrate.', 'İyi bir kahvaltı konsantre olmana yardımcı olur.'),
      w('restaurant', 'restoran', 'A2', 'We met at a restaurant near campus.', 'Kampüs yakınındaki bir restoranda buluştuk.'),
      w('recipe', 'tarif', 'A2', 'She followed a simple recipe online.', 'Çevrimiçi basit bir tarifi takip etti.'),
      w('organic', 'organik', 'B1', 'Organic food often costs more.', 'Organik gıda genellikle daha pahalıdır.'),
      w('vegetarian', 'vejetaryen', 'B1', 'The cafeteria offers vegetarian meals.', 'Yemekhane vejetaryen yemekler sunuyor.'),
      w('calorie', 'kalori', 'B1', 'Check calories on packaged food labels.', 'Paketli gıda etiketlerindeki kalorilere bak.'),
      w('protein', 'protein', 'B1', 'Athletes need enough protein every day.', 'Sporcular her gün yeterli proteine ihtiyaç duyar.'),
      w('allergy', 'alerji', 'B1', 'Nut allergy can be very serious.', 'Fındık alerjisi çok ciddi olabilir.'),
      w('harvest', 'hasat', 'B1', 'The harvest was poor because of drought.', 'Kuraklık yüzünden hasat zayıftı.'),
      w('cuisine', 'mutfak, yemek kültürü', 'B1', 'Turkish cuisine is famous worldwide.', 'Türk mutfağı dünya çapında ünlüdür.'),
      w('malnutrition', 'yetersiz beslenme', 'B1', 'Malnutrition affects child development.', 'Yetersiz beslenme çocuk gelişimini etkiler.'),
      w('additives', 'katkı maddeleri', 'B1', 'Some additives preserve food longer.', 'Bazı katkı maddeleri gıdayı daha uzun korur.'),
      w('scarcity', 'kıtlık', 'B1', 'Water scarcity affects farming regions.', 'Su kıtlığı tarım bölgelerini etkiler.'),
      w('consumption', 'tüketim', 'B1', 'Meat consumption is falling in some cities.', 'Bazı şehirlerde et tüketimi düşüyor.'),
      w('fortification', 'zenginleştirme', 'B1+', 'Fortification of flour adds essential vitamins.', 'Unun zenginleştirilmesi temel vitaminler ekler.'),
      w('artisanal', 'el yapımı, geleneksel', 'B1+', 'Artisanal cheese sells well at local markets.', 'El yapımı peynir yerel pazarlarda iyi satılır.'),
      w('ultra-processed', 'ultra işlenmiş', 'B1+', 'Ultra-processed snacks harm long-term health.', 'Ultra işlenmiş atıştırmalıklar uzun vadeli sağlığa zarar verir.'),
      w('agribusiness', 'tarım işletmeciliği', 'B1+', 'Agribusiness dominates many supply chains.', 'Tarım işletmeciliği birçok tedarik zincirine hakimdir.'),
      w('monoculture', 'tek tip tarım', 'B1+', 'Monoculture reduces soil quality over time.', 'Tek tip tarım zamanla toprak kalitesini düşürür.'),
      w('traceability', 'izlenebilirlik', 'B1+', 'Traceability helps track unsafe food batches.', 'İzlenebilirlik güvensiz gıda partilerinin takibine yardımcı olur.'),
      w('plant-based', 'bitki bazlı', 'B1+', 'Plant-based diets reduce environmental impact.', 'Bitki bazlı diyetler çevresel etkiyi azaltır.'),
      w('subsistence', 'geçim', 'B1+', 'Subsistence farming feeds many rural families.', 'Geçim tarımı birçok kırsal aileyi besler.'),
    ],
  },
  {
    anchor: 'housing',
    titleTr: 'Konut ve Şehir',
    titleEn: 'Housing and City',
    words: [
      w('house', 'ev', 'A2', 'They rent a small house near campus.', 'Kampüs yakınında küçük bir ev kiralıyorlar.'),
      w('flat', 'daire', 'A2', 'My flat has two bedrooms and a balcony.', 'Dairemin iki yatak odası ve bir balkonu var.'),
      w('rent', 'kira', 'A2', 'Rent is due on the first of the month.', 'Kira ayın birinde ödenir.'),
      w('room', 'oda', 'A2', 'Students share a room to save money.', 'Öğrenciler para biriktirmek için oda paylaşır.'),
      w('street', 'sokak, cadde', 'A2', 'Our street is quiet at night.', 'Sokağımız gece sessizdir.'),
      w('building', 'bina', 'A2', 'The building has an elevator and security.', 'Binada asansör ve güvenlik var.'),
      w('neighbour', 'komşu', 'A2', 'My neighbour works at the hospital.', 'Komşum hastanede çalışıyor.'),
      w('furniture', 'mobilya', 'A2', 'We bought cheap furniture for the flat.', 'Daire için ucuz mobilya aldık.'),
      w('mortgage', 'ipotek kredisi', 'B1', 'A mortgage takes many years to repay.', 'İpotek kredisinin geri ödenmesi yıllar sürer.'),
      w('landlord', 'ev sahibi', 'B1', 'The landlord fixed the broken heater.', 'Ev sahibi bozuk kaloriferi tamir etti.'),
      w('tenant', 'kiracı', 'B1', 'Tenants must report damage quickly.', 'Kiracılar hasarı hızlıca bildirmelidir.'),
      w('urban', 'kentsel', 'B1', 'Urban areas grow faster than villages.', 'Kentsel alanlar köylerden daha hızlı büyür.'),
      w('suburb', 'banliyö', 'B1', 'Many families live in the suburbs.', 'Birçok aile banliyöde yaşar.'),
      w('renovation', 'yenileme', 'B1', 'Renovation increased the value of the flat.', 'Yenileme dairenin değerini artırdı.'),
      w('overcrowding', 'aşırı kalabalık', 'B1', 'Overcrowding is common in student housing.', 'Öğrenci konutlarında aşırı kalabalık yaygındır.'),
      w('utilities', 'faturalar, kamu hizmetleri', 'B1', 'Utilities include water, gas and electricity.', 'Faturalar su, gaz ve elektriği içerir.'),
      w('zoning', 'imar planlaması', 'B1', 'Zoning laws limit building height.', 'İmar yasaları bina yüksekliğini sınırlar.'),
      w('gentrification', 'soylulaştırma', 'B1', 'Gentrification pushes rents up in old districts.', 'Soylulaştırma eski mahallelerde kiraları artırır.'),
      w('homelessness', 'evsizlik', 'B1', 'Homelessness needs long-term policy solutions.', 'Evsizlik uzun vadeli politika çözümleri gerektirir.'),
      w('affordable', 'uygun fiyatlı', 'B1+', 'Students need affordable housing near campus.', 'Öğrencilerin kampüs yakınında uygun fiyatlı konuta ihtiyacı var.'),
      w('condominium', 'kat mülkiyetli daire', 'B1+', 'They bought a condominium downtown.', 'Şehir merkezinde kat mülkiyetli daire aldılar.'),
      w('densification', 'yoğunlaştırma', 'B1+', 'Urban densification can reduce sprawl.', 'Kentsel yoğunlaştırma yayılımı azaltabilir.'),
      w('informal', 'gayri resmi', 'B1+', 'Informal settlements lack basic services.', 'Gayri resmi yerleşimler temel hizmetlerden yoksundur.'),
      w('retrofitting', 'iyileştirme', 'B1+', 'Retrofitting old buildings saves energy.', 'Eski binaların iyileştirilmesi enerji tasarrufu sağlar.'),
      w('walkability', 'yürünebilirlik', 'B1+', 'Walkability improves quality of life in cities.', 'Yürünebilirlik şehirlerde yaşam kalitesini artırır.'),
      w('mixed-use', 'karma kullanım', 'B1+', 'Mixed-use blocks combine shops and homes.', 'Karma kullanım blokları dükkan ve evleri birleştirir.'),
      w('eviction', 'tahliye', 'B1+', 'Unfair eviction harms vulnerable tenants.', 'Haksız tahliye savunmasız kiracılara zarar verir.'),
    ],
  },
  {
    anchor: 'family',
    titleTr: 'Aile ve İlişkiler',
    titleEn: 'Family and Relationships',
    words: [
      w('mother', 'anne', 'A2', 'My mother calls me every Sunday.', 'Annem her Pazar beni arar.'),
      w('father', 'baba', 'A2', 'His father retired last year.', 'Babası geçen yıl emekli oldu.'),
      w('child', 'çocuk', 'A2', 'Every child needs love and support.', 'Her çocuğun sevgi ve desteğe ihtiyacı vardır.'),
      w('brother', 'erkek kardeş', 'A2', 'My brother studies at the same university.', 'Erkek kardeşim aynı üniversitede okuyor.'),
      w('sister', 'kız kardeş', 'A2', 'Her sister lives in another city.', 'Kız kardeşi başka bir şehirde yaşıyor.'),
      w('wedding', 'düğün', 'A2', 'We attended a family wedding in June.', 'Haziran\'da bir aile düğününe katıldık.'),
      w('cousin', 'kuzen', 'A2', 'My cousin helped me move to Gaziantep.', 'Kuzenim Gaziantep\'e taşınmama yardım etti.'),
      w('grandparent', 'büyükanne/büyükbaba', 'A2', 'Grandparents often live with younger families.', 'Büyükanne ve büyükbabalar genelde genç ailelerle yaşar.'),
      w('divorce', 'boşanma', 'B1', 'Divorce affects children emotionally.', 'Boşanma çocukları duygusal olarak etkiler.'),
      w('marriage', 'evlilik', 'B1', 'Marriage traditions vary between cultures.', 'Evlilik gelenekleri kültürler arasında farklıdır.'),
      w('sibling', 'kardeş', 'B1', 'Sibling rivalry is common but usually harmless.', 'Kardeş rekabeti yaygındır ama genelde zararsızdır.'),
      w('household', 'hane', 'B1', 'Average household size is falling in cities.', 'Ortalama hane büyüklüğü şehirlerde düşüyor.'),
      w('parenting', 'ebeveynlik', 'B1', 'Positive parenting builds confidence in children.', 'Olumlu ebeveynlik çocuklarda özgüven oluşturur.'),
      w('adoption', 'evlat edinme', 'B1', 'Adoption gives children a stable home.', 'Evlat edinme çocuklara istikrarlı bir yuva verir.'),
      w('kinship', 'akrabalık', 'B1', 'Kinship ties remain strong in rural areas.', 'Akrabalık bağları kırsal bölgelerde güçlü kalır.'),
      w('caregiver', 'bakıcı', 'B1', 'A caregiver supports elderly relatives at home.', 'Bakıcı yaşlı akrabaları evde destekler.'),
      w('single-parent', 'tek ebeveynli', 'B1', 'Single-parent families face financial pressure.', 'Tek ebeveynli aileler mali baskıyla karşılaşır.'),
      w('generation', 'nesil', 'B1', 'Each generation uses technology differently.', 'Her nesil teknolojiyi farklı kullanır.'),
      w('cohabitation', 'birlikte yaşama', 'B1', 'Cohabitation is more accepted than before.', 'Birlikte yaşama eskisinden daha kabul görüyor.'),
      w('intergenerational', 'nesiller arası', 'B1+', 'Intergenerational learning benefits young and old.', 'Nesiller arası öğrenme genç ve yaşlıya fayda sağlar.'),
      w('nuclear', 'çekirdek (aile)', 'B1+', 'The nuclear family model is still common.', 'Çekirdek aile modeli hâlâ yaygındır.'),
      w('estrangement', 'yabancılaşma', 'B1+', 'Long estrangement can hurt family bonds.', 'Uzun yabancılaşma aile bağlarına zarar verebilir.'),
      w('fertility', 'doğurganlık', 'B1+', 'Fertility rates influence future population size.', 'Doğurganlık oranları gelecekteki nüfus büyüklüğünü etkiler.'),
      w('matriarchal', 'anaerkil', 'B1+', 'Some societies have matriarchal family structures.', 'Bazı toplumlarda anaerkil aile yapıları vardır.'),
      w('patriarchal', 'ataerkil', 'B1+', 'Patriarchal norms are changing in many countries.', 'Ataerkil normlar birçok ülkede değişiyor.'),
      w('reconciliation', 'uzlaşma', 'B1+', 'Family reconciliation takes time and honesty.', 'Aile içi uzlaşma zaman ve dürüstlük gerektirir.'),
      w('dependency', 'bağımlılık', 'B1+', 'Economic dependency can trap young adults at home.', 'Ekonomik bağımlılık genç yetişkinleri evde tutabilir.'),
    ],
  },
  {
    anchor: 'emotions',
    titleTr: 'Duygular ve Kişilik',
    titleEn: 'Emotions and Personality',
    words: [
      w('happy', 'mutlu', 'A2', 'She felt happy after passing the exam.', 'Sınavı geçince mutlu hissetti.'),
      w('sad', 'üzgün', 'A2', 'He was sad when his friend moved away.', 'Arkadaşı taşınınca üzgündü.'),
      w('angry', 'kızgın', 'A2', 'Do not send emails when you are angry.', 'Kızgınken e-posta gönderme.'),
      w('tired', 'yorgun', 'A2', 'Students often feel tired during exam week.', 'Öğrenciler sınav haftasında sık sık yorgun hisseder.'),
      w('afraid', 'korkmuş', 'A2', 'Many people are afraid of public speaking.', 'Birçok kişi topluluk önünde konuşmaktan korkar.'),
      w('nervous', 'gergin', 'A2', 'I get nervous before presentations.', 'Sunumlardan önce gergin olurum.'),
      w('proud', 'gururlu', 'A2', 'Parents are proud of their children\'s success.', 'Ebeveynler çocuklarının başarısıyla gurur duyar.'),
      w('lonely', 'yalnız', 'A2', 'Living alone can feel lonely at first.', 'Yalnız yaşamak başta yalnız hissettirebilir.'),
      w('anxious', 'kaygılı', 'B1', 'Students feel anxious before final exams.', 'Öğrenciler final sınavlarından önce kaygılı hisseder.'),
      w('confident', 'kendine güvenen', 'B1', 'Practice makes you more confident in writing.', 'Pratik yazmada daha kendine güvenmeni sağlar.'),
      w('frustrated', 'hayal kırıklığına uğramış', 'B1', 'He felt frustrated with slow internet.', 'Yavaş internetten hayal kırıklığına uğradı.'),
      w('grateful', 'minnettar', 'B1', 'I am grateful for my teacher\'s feedback.', 'Öğretmenimin geri bildirimi için minnettarım.'),
      w('embarrassed', 'utanmış', 'B1', 'She was embarrassed by her spelling mistake.', 'Yazım hatası yüzünden utandı.'),
      w('optimistic', 'iyimser', 'B1', 'An optimistic attitude helps during hard times.', 'İyimser bir tutum zor zamanlarda yardımcı olur.'),
      w('pessimistic', 'kötümser', 'B1', 'Pessimistic news can affect public mood.', 'Kötümser haberler kamu ruh halini etkileyebilir.'),
      w('empathy', 'empati', 'B1', 'Empathy improves teamwork in class projects.', 'Empati sınıf projelerinde ekip çalışmasını iyileştirir.'),
      w('resilient', 'dayanıklı', 'B1', 'Resilient students recover from failure faster.', 'Dayanıklı öğrenciler başarısızlıktan daha hızlı toparlanır.'),
      w('motivated', 'motivasyonlu', 'B1', 'Clear goals keep you motivated to study.', 'Net hedefler çalışmak için seni motive tutar.'),
      w('stressful', 'stresli', 'B1', 'Exam season is stressful for many students.', 'Sınav dönemi birçok öğrenci için streslidir.'),
      w('melancholy', 'hüzünlü', 'B1+', 'Autumn weather sometimes brings melancholy feelings.', 'Sonbahar havası bazen hüzünlü duygular getirir.'),
      w('contentment', 'memnuniyet', 'B1+', 'Simple routines can bring deep contentment.', 'Basit rutinler derin memnuniyet getirebilir.'),
      w('apprehensive', 'endişeli', 'B1+', 'She felt apprehensive about studying abroad.', 'Yurtdışında okumak konusunda endişeliydi.'),
      w('impulsive', 'dürtüsel', 'B1+', 'Impulsive decisions can harm relationships.', 'Dürtüsel kararlar ilişkilere zarar verebilir.'),
      w('introverted', 'içe dönük', 'B1+', 'Introverted people may prefer quiet study spaces.', 'İçe dönük insanlar sessiz çalışma alanlarını tercih edebilir.'),
      w('extroverted', 'dışa dönük', 'B1+', 'Extroverted students enjoy group discussions.', 'Dışa dönük öğrenciler grup tartışmalarından hoşlanır.'),
      w('conscientious', 'özenli', 'B1+', 'Conscientious learners meet deadlines reliably.', 'Özenli öğrenciler teslim tarihlerine güvenilir şekilde uyar.'),
      w('vulnerable', 'savunmasız', 'B1+', 'Criticism can make anyone feel vulnerable.', 'Eleştiri herkesi savunmasız hissettirebilir.'),
    ],
  },
  {
    anchor: 'science',
    titleTr: 'Bilim ve Araştırma',
    titleEn: 'Science and Research',
    words: [
      w('science', 'bilim', 'A2', 'Science class includes experiments.', 'Fen dersi deneyleri içerir.'),
      w('lab', 'laboratuvar', 'A2', 'Students must wear coats in the lab.', 'Öğrenciler laboratuvarda önlük giymelidir.'),
      w('data', 'veri', 'A2', 'Collect data before you write the report.', 'Raporu yazmadan önce veri topla.'),
      w('test', 'test, deneme', 'A2', 'The test showed the water was clean.', 'Test suyun temiz olduğunu gösterdi.'),
      w('fact', 'gerçek, olgu', 'A2', 'Check every fact in your essay.', 'Makalendeki her gerçeği kontrol et.'),
      w('theory', 'teori', 'A2', 'Darwin\'s theory changed biology.', 'Darwin\'in teorisi biyolojiyi değiştirdi.'),
      w('experiment', 'deney', 'A2', 'Our experiment failed the first time.', 'Deneyimiz ilk seferde başarısız oldu.'),
      w('result', 'sonuç', 'A2', 'The results support our main idea.', 'Sonuçlar ana fikrimizi destekliyor.'),
      w('hypothesis', 'hipotez', 'B1', 'We tested the hypothesis with new data.', 'Hipotezi yeni verilerle test ettik.'),
      w('variable', 'değişken', 'B1', 'Change one variable at a time.', 'Bir seferde bir değişkeni değiştir.'),
      w('sample', 'örneklem', 'B1', 'The sample included two hundred students.', 'Örneklem iki yüz öğrenciyi içerdi.'),
      w('finding', 'bulgu', 'B1', 'The main finding surprised the research team.', 'Ana bulgu araştırma ekibini şaşırttı.'),
      w('analysis', 'analiz', 'B1', 'Statistical analysis takes time to learn.', 'İstatistiksel analiz öğrenmek zaman alır.'),
      w('laboratory', 'laboratuvar', 'B1', 'The laboratory is closed on weekends.', 'Laboratuvar hafta sonları kapalıdır.'),
      w('peer-reviewed', 'hakemli', 'B1', 'Use peer-reviewed articles in your essay.', 'Makalende hakemli makaleler kullan.'),
      w('methodology', 'yöntem bilimi', 'B1', 'Clear methodology improves research quality.', 'Net yöntem bilimi araştırma kalitesini artırır.'),
      w('replicate', 'tekrarlamak, çoğaltmak', 'B1', 'Other teams could not replicate the findings.', 'Diğer ekipler bulguları tekrarlayamadı.'),
      w('empirical', 'ampirik, deneysel', 'B1', 'Empirical studies rely on observed data.', 'Ampirik çalışmalar gözlemlenen veriye dayanır.'),
      w('quantitative', 'nicel', 'B1', 'Quantitative methods use numbers and statistics.', 'Nicel yöntemler sayı ve istatistik kullanır.'),
      w('longitudinal', 'boylamsal', 'B1+', 'A longitudinal study followed students for five years.', 'Boylamsal bir çalışma öğrencileri beş yıl izledi.'),
      w('paradigm', 'paradigma', 'B1+', 'The new paradigm changed medical research.', 'Yeni paradigma tıbbi araştırmayı değiştirdi.'),
      w('correlation', 'korelasyon', 'B1+', 'Correlation does not always mean causation.', 'Korelasyon her zaman nedensellik anlamına gelmez.'),
      w('validity', 'geçerlilik', 'B1+', 'Researchers checked the validity of the survey.', 'Araştırmacılar anketin geçerliliğini kontrol etti.'),
      w('randomised', 'rastgele', 'B1+', 'A randomised trial reduced bias in results.', 'Rastgele bir deneme sonuçlardaki önyargıyı azalttı.'),
      w('interdisciplinary', 'disiplinler arası', 'B1+', 'Interdisciplinary teams solve complex problems.', 'Disiplinler arası ekipler karmaşık sorunları çözer.'),
      w('breakthrough', 'çığır açan buluş', 'B1+', 'The vaccine was a major scientific breakthrough.', 'Aşı büyük bir bilimsel çığır açan buluştu.'),
      w('falsifiable', 'yanıltılabilir', 'B1+', 'Good theories must be falsifiable in principle.', 'İyi teoriler ilke olarak yanıltılabilir olmalıdır.'),
    ],
  },
  {
    anchor: 'culture',
    titleTr: 'Kültür, Sanat ve Medya',
    titleEn: 'Culture, Arts and Media',
    words: [
      w('music', 'müzik', 'A2', 'She listens to music while studying.', 'Çalışırken müzik dinler.'),
      w('film', 'film', 'A2', 'We watched a film about Turkish history.', 'Türk tarihi hakkında bir film izledik.'),
      w('book', 'kitap', 'A2', 'The library has thousands of books.', 'Kütüphanede binlerce kitap var.'),
      w('museum', 'müze', 'A2', 'The museum opens at ten in the morning.', 'Müze sabah onda açılıyor.'),
      w('festival', 'festival', 'A2', 'The city festival attracts many visitors.', 'Şehir festivali birçok ziyaretçi çeker.'),
      w('tradition', 'gelenek', 'A2', 'Family tradition includes special holiday meals.', 'Aile geleneği özel bayram yemeklerini içerir.'),
      w('art', 'sanat', 'A2', 'Art students visited the gallery yesterday.', 'Sanat öğrencileri dün galeriyi ziyaret etti.'),
      w('news', 'haber', 'A2', 'Check the news before writing your essay topic.', 'Makale konunu yazmadan önce haberleri kontrol et.'),
      w('heritage', 'miras', 'B1', 'UNESCO protects world cultural heritage.', 'UNESCO dünya kültürel mirasını korur.'),
      w('literature', 'edebiyat', 'B1', 'Turkish literature includes many famous poets.', 'Türk edebiyatı birçok ünlü şairi içerir.'),
      w('documentary', 'belgesel', 'B1', 'The documentary explained climate change clearly.', 'Belgesel iklim değişikliğini açıkça anlattı.'),
      w('censorship', 'sansür', 'B1', 'Censorship limits freedom of the press.', 'Sansür basın özgürlüğünü sınırlar.'),
      w('broadcast', 'yayın', 'B1', 'The broadcast reached millions of viewers.', 'Yayın milyonlarca izleyiciye ulaştı.'),
      w('exhibition', 'sergi', 'B1', 'The exhibition shows modern Gaziantep crafts.', 'Sergi modern Gaziantep el sanatlarını gösteriyor.'),
      w('folklore', 'folklor', 'B1', 'Local folklore inspires regional music.', 'Yerel folklor bölgesel müziğe ilham verir.'),
      w('journalism', 'gazetecilik', 'B1', 'Good journalism checks facts carefully.', 'İyi gazetecilik gerçekleri dikkatle kontrol eder.'),
      w('archaeology', 'arkeoloji', 'B1', 'Archaeology uncovered ancient city walls.', 'Arkeoloji antik şehir duvarlarını ortaya çıkardı.'),
      w('multicultural', 'çok kültürlü', 'B1', 'Universities are increasingly multicultural.', 'Üniversiteler giderek daha çok kültürlü.'),
      w('performing', 'sahne sanatları', 'B1', 'Performing arts include theatre and dance.', 'Sahne sanatları tiyatro ve dansı içerir.'),
      w('aesthetic', 'estetik', 'B1+', 'The building has strong aesthetic value.', 'Binanın güçlü estetik değeri var.'),
      w('patronage', 'himaye, destek', 'B1+', 'Royal patronage funded many Renaissance works.', 'Kraliyet himayesi birçok Rönesans eserini finanse etti.'),
      w('vernacular', 'yerel dil', 'B1+', 'Writers used the vernacular to reach common readers.', 'Yazarlar sıradan okuyuculara ulaşmak için yerel dili kullandı.'),
      w('propaganda', 'propaganda', 'B1+', 'Wartime propaganda influenced public opinion.', 'Savaş zamanı propagandası kamuoyunu etkiledi.'),
      w('postmodern', 'postmodern', 'B1+', 'Postmodern art questions traditional meaning.', 'Postmodern sanat geleneksel anlamı sorgular.'),
      w('digitised', 'dijitalleştirilmiş', 'B1+', 'Digitised archives help researchers worldwide.', 'Dijitalleştirilmiş arşivler dünya çapında araştırmacılara yardımcı olur.'),
      w('anthropology', 'antropoloji', 'B1+', 'Anthropology studies human societies and customs.', 'Antropoloji insan topluluklarını ve geleneklerini inceler.'),
      w('curatorship', 'küratörlük', 'B1+', 'Professional curatorship improves museum displays.', 'Profesyonel küratörlük müze sergilerini iyileştirir.'),
    ],
  },
  {
    anchor: 'sports',
    titleTr: 'Spor ve Boş Zaman',
    titleEn: 'Sports and Leisure',
    words: [
      w('football', 'futbol', 'A2', 'Students play football after classes.', 'Öğrenciler derslerden sonra futbol oynar.'),
      w('swim', 'yüzmek', 'A2', 'I swim twice a week at the pool.', 'Havuzda haftada iki kez yüzerim.'),
      w('run', 'koşmak', 'A2', 'He runs in the park every morning.', 'Her sabah parkta koşar.'),
      w('team', 'takım', 'A2', 'Our team won the university tournament.', 'Takımımız üniversite turnuvasını kazandı.'),
      w('match', 'maç', 'A2', 'The match started at seven in the evening.', 'Maç akşam yedide başladı.'),
      w('coach', 'antrenör', 'A2', 'The coach trains players three times a week.', 'Antrenör oyuncuları haftada üç kez çalıştırır.'),
      w('gym', 'spor salonu', 'A2', 'The campus gym is cheap for students.', 'Kampüs spor salonu öğrenciler için ucuz.'),
      w('hobby', 'hobi', 'A2', 'Photography is my favourite hobby.', 'Fotoğrafçılık en sevdiğim hobim.'),
      w('competition', 'yarışma', 'B1', 'She entered a national writing competition.', 'Ulusal bir yazı yarışmasına katıldı.'),
      w('athlete', 'sporcu', 'B1', 'The athlete follows a strict training plan.', 'Sporcu sıkı bir antrenman planı uygular.'),
      w('fitness', 'form, zindelik', 'B1', 'Regular fitness improves mental health.', 'Düzenli zindelik ruh sağlığını iyileştirir.'),
      w('leisure', 'boş zaman', 'B1', 'Leisure activities reduce study stress.', 'Boş zaman aktiviteleri ders stresini azaltır.'),
      w('stadium', 'stadyum', 'B1', 'The stadium was full during the final.', 'Final sırasında stadyum doluydu.'),
      w('referee', 'hakem', 'B1', 'The referee stopped the game for injury.', 'Hakem sakatlık için oyunu durdurdu.'),
      w('spectator', 'seyirci', 'B1', 'Thousands of spectators watched the match.', 'Binlerce seyirci maçı izledi.'),
      w('recreation', 'dinlence', 'B1', 'Parks provide space for recreation.', 'Parklar dinlenme için alan sağlar.'),
      w('endurance', 'dayanıklılık', 'B1', 'Long races test an athlete\'s endurance.', 'Uzun yarışlar sporcunun dayanıklılığını test eder.'),
      w('amateur', 'amatör', 'B1', 'Amateur clubs welcome new members.', 'Amatör kulüpler yeni üyeleri karşılar.'),
      w('doping', 'doping', 'B1', 'Doping scandals damage sport credibility.', 'Doping skandalları sporun güvenilirliğine zarar verir.'),
      w('marathon', 'maraton', 'B1+', 'She trained six months for the marathon.', 'Maraton için altı ay antrenman yaptı.'),
      w('calisthenics', 'kalistenik', 'B1', 'Calisthenics classes need no special equipment.', 'Kalistenik dersleri özel ekipman gerektirmez.'),
      w('rehabilitate', 'rehabilite etmek', 'B1+', 'Physio helps athletes rehabilitate after injury.', 'Fizyoterapi sporcuların sakatlık sonrası rehabilitasyonuna yardımcı olur.'),
      w('sportsmanship', 'sportmenlik', 'B1+', 'Good sportsmanship matters more than winning.', 'İyi sportmenlik kazanmaktan daha önemlidir.'),
      w('inclusivity', 'kapsayıcılık', 'B1+', 'Inclusivity in sport welcomes all abilities.', 'Sporde kapsayıcılık tüm yetenekleri karşılar.'),
      w('overtraining', 'aşırı antrenman', 'B1+', 'Overtraining can cause fatigue and injury.', 'Aşırı antrenman yorgunluk ve sakatlığa yol açabilir.'),
      w('wellness', 'sağlıklı yaşam', 'B1+', 'Campus wellness programmes offer yoga classes.', 'Kampüs sağlıklı yaşam programları yoga dersleri sunar.'),
      w('extracurricular', 'ders dışı', 'B1+', 'Extracurricular sport builds teamwork skills.', 'Ders dışı spor ekip çalışması becerileri oluşturur.'),
    ],
  },
  {
    anchor: 'opinion',
    titleTr: 'Görüş ve Tartışma (writing)',
    titleEn: 'Opinion and Argument (writing)',
    words: [
      w('think', 'düşünmek', 'A2', 'I think online learning is useful.', 'Çevrimiçi öğrenmenin faydalı olduğunu düşünüyorum.'),
      w('believe', 'inanmak', 'A2', 'Many people believe education reduces poverty.', 'Birçok kişi eğitimin yoksulluğu azalttığına inanır.'),
      w('agree', 'katılmak', 'A2', 'I agree with your main point.', 'Ana fikrine katılıyorum.'),
      w('disagree', 'katılmamak', 'A2', 'Some experts disagree on this issue.', 'Bazı uzmanlar bu konuda hemfikir değil.'),
      w('prefer', 'tercih etmek', 'A2', 'I prefer writing essays to oral exams.', 'Sözlü sınavlara göre makale yazmayı tercih ederim.'),
      w('opinion', 'görüş', 'A2', 'In my opinion, public transport should be cheaper.', 'Bence toplu taşıma daha ucuz olmalı.'),
      w('argue', 'tartışmak, savunmak', 'A2', 'Writers argue that taxes fund schools.', 'Yazarlar vergilerin okulları finanse ettiğini savunur.'),
      w('support', 'desteklemek', 'A2', 'These facts support your argument.', 'Bu gerçekler argümanını destekler.'),
      w('claim', 'iddia etmek', 'B1', 'Critics claim the policy failed.', 'Eleştirmenler politikanın başarısız olduğunu iddia ediyor.'),
      w('maintain', 'savunmak, sürdürmek', 'B1', 'The author maintains that change is necessary.', 'Yazar değişikliğin gerekli olduğunu savunuyor.'),
      w('persuade', 'ikna etmek', 'B1', 'Good examples persuade the reader.', 'İyi örnekler okuyucuyu ikna eder.'),
      w('convince', 'inandırmak', 'B1', 'Statistics can convince sceptical readers.', 'İstatistikler şüpheci okuyucuları inandırabilir.'),
      w('acknowledge', 'kabul etmek', 'B1', 'Acknowledge opposing views in your essay.', 'Makalende karşıt görüşleri kabul et.'),
      w('emphasise', 'vurgulamak', 'B1', 'The introduction should emphasise the thesis.', 'Giriş tezi vurgulamalıdır.'),
      w('contend', 'ileri sürmek', 'B1', 'Some scholars contend that technology helps learning.', 'Bazı bilim insanları teknolojinin öğrenmeye yardımcı olduğunu ileri sürer.'),
      w('assert', 'iddia etmek, ileri sürmek', 'B1', 'The report asserts that pollution is rising.', 'Rapor kirliliğin arttığını ileri sürüyor.'),
      w('refute', 'çürütmek', 'B1', 'You must refute weak counter-arguments.', 'Zayıf karşı argümanları çürütmelisin.'),
      w('stance', 'tutum, duruş', 'B1', 'State your stance clearly in paragraph one.', 'Birinci paragrafta tutumunu açıkça belirt.'),
      w('subjective', 'öznel', 'B1', 'Personal blogs are often subjective.', 'Kişisel bloglar genellikle özneldir.'),
      w('impartial', 'tarafsız', 'B1+', 'Academic writing should be impartial.', 'Akademik yazım tarafsız olmalıdır.'),
      w('contentious', 'tartışmalı', 'B1+', 'Immigration is a contentious political topic.', 'Göç tartışmalı bir siyasi konudur.'),
      w('compelling', 'ikna edici', 'B1+', 'She gave a compelling argument for reform.', 'Reform için ikna edici bir argüman sundu.'),
      w('nuanced', 'nüanslı', 'B1+', 'A nuanced opinion considers both sides.', 'Nüanslı bir görüş her iki tarafı da dikkate alır.'),
      w('polarising', 'kutuplaştırıcı', 'B1+', 'The debate became polarising on social media.', 'Tartışma sosyal medyada kutuplaştırıcı hale geldi.'),
      w('rhetorical', 'retorik', 'B1+', 'He used a rhetorical question in the conclusion.', 'Sonuçta retorik bir soru kullandı.'),
      w('advocate', 'savunucu olmak', 'B1+', 'Many NGOs advocate for cleaner cities.', 'Birçok STK daha temiz şehirler için savunuculuk yapar.'),
      w('rebuttal', 'karşı çıkış', 'B1+', 'Include a rebuttal to strengthen your essay.', 'Makaleni güçlendirmek için bir karşı çıkış ekle.'),
    ],
  },
  {
    anchor: 'cause-effect',
    titleTr: 'Sebep, Sonuç ve Bağlaçlar (writing)',
    titleEn: 'Cause, Effect and Connectors (writing)',
    words: [
      w('because', 'çünkü', 'A2', 'Students study hard because exams are near.', 'Öğrenciler sınavlar yakın olduğu için çok çalışır.'),
      w('so', 'bu yüzden', 'A2', 'It rained, so the match was cancelled.', 'Yağmur yağdı, bu yüzden maç iptal edildi.'),
      w('if', 'eğer', 'A2', 'If pollution rises, health costs increase.', 'Kirlilik artarsa sağlık maliyetleri yükselir.'),
      w('when', 'ne zaman, -dığında', 'A2', 'When prices rise, families save less.', 'Fiyatlar yükseldiğinde aileler daha az biriktirir.'),
      w('then', 'sonra, o zaman', 'A2', 'First plan, then write your essay.', 'Önce planla, sonra makaleni yaz.'),
      w('although', 'rağmen', 'A2', 'Although it was late, she finished the essay.', 'Geç olmasına rağmen makaleyi bitirdi.'),
      w('however', 'ancak', 'A2', 'The idea is good; however, it costs too much.', 'Fikir iyi; ancak çok pahalı.'),
      w('therefore', 'bu nedenle', 'A2', 'Costs rose; therefore, fewer students enrolled.', 'Maliyetler arttı; bu nedenle daha az öğrenci kayıt yaptı.'),
      w('consequently', 'sonuç olarak', 'B1', 'Taxes fell and, consequently, services were cut.', 'Vergiler düştü ve sonuç olarak hizmetler kesildi.'),
      w('thus', 'böylece', 'B1', 'The data were clear; thus, we changed policy.', 'Veriler açıktı; böylece politikayı değiştirdik.'),
      w('hence', 'dolayısıyla', 'B1', 'Demand fell, hence prices dropped.', 'Talep düştü, dolayısıyla fiyatlar düştü.'),
      w('owing to', 'nedeniyle', 'B1', 'Owing to drought, harvests were poor.', 'Kuraklık nedeniyle hasatlar zayıftı.'),
      w('due to', 'yüzünden', 'B1', 'Flights were delayed due to fog.', 'Sis yüzünden uçuşlar gecikti.'),
      w('trigger', 'tetiklemek', 'B1', 'One event can trigger wider protests.', 'Tek bir olay daha geniş protestoları tetikleyebilir.'),
      w('lead to', 'yol açmak', 'B1', 'Poor diet can lead to serious illness.', 'Kötü beslenme ciddi hastalığa yol açabilir.'),
      w('result in', 'ile sonuçlanmak', 'B1', 'The reform resulted in higher enrolment.', 'Reform daha yüksek kayıtla sonuçlandı.'),
      w('stem from', 'kaynaklanmak', 'B1', 'Many problems stem from inequality.', 'Birçok sorun eşitsizlikten kaynaklanır.'),
      w('whereas', 'oysa, halbuki', 'B1', 'Cities grew fast, whereas villages shrank.', 'Şehirler hızla büyüdü, oysa köyler küçüldü.'),
      w('nevertheless', 'yine de', 'B1', 'It was expensive; nevertheless, they bought it.', 'Pahalıydı; yine de satın aldılar.'),
      w('notwithstanding', 'rağmen', 'B1+', 'Notwithstanding the risks, they invested.', 'Risklere rağmen yatırım yaptılar.'),
      w('accordingly', 'buna göre', 'B1+', 'Rules changed; accordingly, schools adapted.', 'Kurallar değişti; buna göre okullar uyum sağladı.'),
      w('subsequently', 'ardından', 'B1+', 'The law passed and subsequently took effect.', 'Yasa geçti ve ardından yürürlüğe girdi.'),
      w('precipitate', 'hızlandırmak, tetiklemek', 'B1+', 'The scandal may precipitate political change.', 'Skandal siyasi değişimi hızlandırabilir.'),
      w('exacerbate', 'kötüleştirmek', 'B1+', 'Heatwaves exacerbate water shortages.', 'Sıcak dalgaları su kıtlığını kötüleştirir.'),
      w('mitigate', 'hafifletmek', 'B1+', 'Trees mitigate urban heat islands.', 'Ağaçlar kentsel ısı adalarını hafifletir.'),
      w('corollary', 'doğal sonuç', 'B1+', 'A corollary of growth is higher energy use.', 'Büyümenin doğal sonucu daha yüksek enerji kullanımıdır.'),
      w('ramification', 'sonuç, dalgalanma', 'B1+', 'Consider the ramifications before changing law.', 'Yasayı değiştirmeden önce sonuçlarını düşün.'),
    ],
  },
  {
    anchor: 'academic-verbs',
    titleTr: 'Akademik Fiiller (writing)',
    titleEn: 'Academic Verbs (writing)',
    words: [
      w('describe', 'tanımlamak, betimlemek', 'A2', 'Describe the chart in your own words.', 'Grafiği kendi kelimelerinle tanımla.'),
      w('explain', 'açıklamak', 'A2', 'Explain why you chose this topic.', 'Bu konuyu neden seçtiğini açıkla.'),
      w('compare', 'karşılaştırmak', 'A2', 'Compare city life with rural life.', 'Şehir yaşamını kırsal yaşamla karşılaştır.'),
      w('show', 'göstermek', 'A2', 'The graph shows a clear increase.', 'Grafik net bir artış gösteriyor.'),
      w('include', 'içermek', 'A2', 'Your essay should include an introduction.', 'Makalen bir giriş içermeli.'),
      w('discuss', 'tartışmak', 'A2', 'Discuss both advantages and disadvantages.', 'Hem avantajları hem dezavantajları tartış.'),
      w('define', 'tanımlamak', 'A2', 'Define key terms in paragraph one.', 'Birinci paragrafta anahtar terimleri tanımla.'),
      w('list', 'listelemek', 'A2', 'List three reasons for your opinion.', 'Görüşün için üç neden listele.'),
      w('analyse', 'analiz etmek', 'B1', 'Analyse the causes of unemployment.', 'İşsizliğin nedenlerini analiz et.'),
      w('evaluate', 'değerlendirmek', 'B1', 'Evaluate the strengths of each argument.', 'Her argümanın güçlü yönlerini değerlendir.'),
      w('summarise', 'özetlemek', 'B1', 'Summarise the article in two sentences.', 'Makaleyi iki cümlede özetle.'),
      w('illustrate', 'örneklemek', 'B1', 'Use data to illustrate your point.', 'Noktanı örneklemek için veri kullan.'),
      w('demonstrate', 'göstermek, kanıtlamak', 'B1', 'The study demonstrates a clear link.', 'Çalışma net bir bağlantı gösteriyor.'),
      w('investigate', 'araştırmak', 'B1', 'Researchers investigate climate impacts.', 'Araştırmacılar iklim etkilerini araştırır.'),
      w('implement', 'uygulamak', 'B1', 'Schools implement new safety rules.', 'Okullar yeni güvenlik kurallarını uygular.'),
      w('constitute', 'oluşturmak', 'B1', 'Women constitute half the student body.', 'Kadınlar öğrenci kitlesinin yarısını oluşturur.'),
      w('derive', 'türetmek, çıkarmak', 'B1', 'Many laws derive from older traditions.', 'Birçok yasa eski geleneklerden türetilir.'),
      w('correlate', 'ilişkilendirmek', 'B1', 'Studies correlate income with health outcomes.', 'Çalışmalar geliri sağlık sonuçlarıyla ilişkilendirir.'),
      w('prioritise', 'önceliklendirmek', 'B1', 'Governments must prioritise public education.', 'Hükümetler kamu eğitimini önceliklendirmelidir.'),
      w('substantiate', 'kanıtlamak, desteklemek', 'B1+', 'You need sources to substantiate your claims.', 'İddialarını kanıtlamak için kaynaklara ihtiyacın var.'),
      w('elucidate', 'aydınlatmak', 'B1+', 'The footnote elucidates a difficult term.', 'Dipnot zor bir terimi aydınlatır.'),
      w('juxtapose', 'yan yana koymak', 'B1+', 'The essay juxtaposes two policy models.', 'Makale iki politika modelini yan yana koyar.'),
      w('extrapolate', 'çıkarım yapmak', 'B1+', 'Do not extrapolate beyond the given data.', 'Verilen verinin ötesinde çıkarım yapma.'),
      w('synthesise', 'sentezlemek', 'B1+', 'Synthesise ideas from several readings.', 'Birkaç okumadan gelen fikirleri sentezle.'),
      w('postulate', 'varsaymak', 'B1+', 'The theory postulates a link between diet and mood.', 'Teori beslenme ile ruh hali arasında bağ varsayar.'),
      w('underscore', 'vurgulamak', 'B1+', 'The results underscore the need for reform.', 'Sonuçlar reform ihtiyacını vurgular.'),
      w('contextualise', 'bağlama oturtmak', 'B1+', 'Contextualise statistics within local history.', 'İstatistikleri yerel tarih içinde bağlama oturt.'),
    ],
  },
  {
    anchor: 'adjectives',
    titleTr: 'Sıfatlar (writing)',
    titleEn: 'Adjectives (writing)',
    words: [
      w('good', 'iyi', 'A2', 'This is a good example for your essay.', 'Bu makalen için iyi bir örnek.'),
      w('bad', 'kötü', 'A2', 'Bad planning leads to weak arguments.', 'Kötü planlama zayıf argümanlara yol açar.'),
      w('big', 'büyük', 'A2', 'A big city offers more job options.', 'Büyük bir şehir daha fazla iş seçeneği sunar.'),
      w('small', 'küçük', 'A2', 'Small changes can improve air quality.', 'Küçük değişiklikler hava kalitesini iyileştirebilir.'),
      w('important', 'önemli', 'A2', 'Education is important for development.', 'Eğitim kalkınma için önemlidir.'),
      w('difficult', 'zor', 'A2', 'Writing formal essays is difficult at first.', 'Resmi makale yazmak başta zordur.'),
      w('popular', 'popüler', 'A2', 'Online courses are popular with students.', 'Çevrimiçi dersler öğrenciler arasında popüler.'),
      w('useful', 'faydalı', 'A2', 'A clear outline is useful when writing.', 'Net bir taslak yazarken faydalıdır.'),
      w('significant', 'önemli, anlamlı', 'B1', 'There is a significant difference between groups.', 'Gruplar arasında anlamlı bir fark var.'),
      w('effective', 'etkili', 'B1', 'Public campaigns can be effective against smoking.', 'Kamu kampanyaları sigaraya karşı etkili olabilir.'),
      w('relevant', 'ilgili, alakalı', 'B1', 'Choose relevant examples for your topic.', 'Konun için ilgili örnekler seç.'),
      w('adequate', 'yeterli', 'B1', 'Adequate funding supports better schools.', 'Yeterli finansman daha iyi okulları destekler.'),
      w('widespread', 'yaygın', 'B1', 'Smartphone use is widespread among youth.', 'Akıllı telefon kullanımı gençler arasında yaygındır.'),
      w('crucial', 'çok önemli', 'B1', 'Clean water is crucial for public health.', 'Temiz su kamu sağlığı için çok önemlidir.'),
      w('feasible', 'uygulanabilir', 'B1', 'The plan seems feasible within the budget.', 'Plan bütçe dahilinde uygulanabilir görünüyor.'),
      w('inevitable', 'kaçınılmaz', 'B1', 'Some job losses may be inevitable.', 'Bazı iş kayıpları kaçınılmaz olabilir.'),
      w('controversial', 'tartışmalı', 'B1', 'Nuclear power remains controversial.', 'Nükleer enerji tartışmalı olmaya devam ediyor.'),
      w('substantial', 'önemli miktarda', 'B1', 'The project received substantial funding.', 'Proje önemli miktarda fon aldı.'),
      w('prevalent', 'yaygın', 'B1', 'Stress is prevalent during exam periods.', 'Stres sınav dönemlerinde yaygındır.'),
      w('paramount', 'en önemli', 'B1+', 'Student safety is of paramount importance.', 'Öğrenci güvenliği en önemli konudur.'),
      w('detrimental', 'zararlı', 'B1+', 'Smoking is detrimental to long-term health.', 'Sigara uzun vadeli sağlığa zararlıdır.'),
      w('indispensable', 'vazgeçilmez', 'B1+', 'Critical thinking is indispensable in academia.', 'Eleştirel düşünme akademide vazgeçilmezdir.'),
      w('unprecedented', 'benzeri görülmemiş', 'B1+', 'The heatwave was unprecedented in scale.', 'Sıcak dalgası ölçek olarak benzeri görülmemişti.'),
      w('profound', 'derin', 'B1+', 'Technology has a profound effect on society.', 'Teknolojinin toplum üzerinde derin bir etkisi var.'),
      w('tenuous', 'zayıf, dayanıksız', 'B1+', 'The link between the two facts is tenuous.', 'İki gerçek arasındaki bağ zayıftır.'),
      w('ubiquitous', 'her yerde bulunan', 'B1+', 'Wi-Fi is ubiquitous on modern campuses.', 'Wi-Fi modern kampüslerde her yerde bulunur.'),
      w('quintessential', 'tipik, öz', 'B1+', 'A clear thesis is quintessential to good essays.', 'Net bir tez iyi makalelerin özüdür.'),
    ],
  },
];
